# Generated by Django 5.2.1 on 2025-06-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportmessage',
            options={},
        ),
    ]
